spring:
  #http://localhost:8090/com/example/demo/v1/h2
  #http://localhost:8090/com/example/demo/v1/external/banks
  datasource:
    driverClassName: org.h2.Driver
    name: DEV_DEMO_DATA
    url: jdbc:h2:mem:testdb;INIT=RUNSCRIPT FROM 'classpath:sql/create_schema.sql';IGNORECASE=TRUE;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=false;MODE=Oracle
    username: sa
    password: sa
    schema: classpath:sql/create_schema.sql
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update # none - is the best to use than create/update dangerous for prod.
  sql:
    init:
      schema-locations: classpath:sql/create_schema.sql #NOT WORK HERE
      mode: always
      platform: always
 