CREATE SCHEMA IF NOT EXISTS DEV_DEMO_DATA;
-- USE DEV_DEMO_DATA;
SET SCHEMA DEV_DEMO_DATA;
-- DROP TABLE IF EXISTS all_sequences;
CREATE TABLE IF NOT EXISTS all_sequences (
    sequence_name VARCHAR(255) NOT NULL,
    next_val BIGINT DEFAULT 1 NOT NULL,
    PRIMARY KEY (sequence_name)
);
-- DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE IF NOT EXISTS ACCOUNT (
    ID INTEGER PRIMARY KEY,
    BALANCE DECIMAL(9,2),
    BANK_ID INTEGER
);
-- DROP TABLE IF EXISTS BANK;
CREATE TABLE IF NOT EXISTS BANK (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(255)
);
-- DROP TABLE IF EXISTS BRANCH;
CREATE TABLE IF NOT EXISTS BRANCH (
    ID INTEGER PRIMARY KEY,
    ADDRESS VARCHAR(255),
    BANK_ID INTEGER
);
-- DROP TABLE IF EXISTS PERSON;
CREATE TABLE IF NOT EXISTS PERSON (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(255)
);
-- DROP TABLE IF EXISTS PERSON_ACCOUNTS;
CREATE TABLE IF NOT EXISTS PERSON_ACCOUNTS (
    OWNERS_ID INTEGER PRIMARY KEY,
    ACCOUNTS_ID INTEGER
);