USE DEV_DEMO_DATA;
INSERT INTO BANK(ID, NAME) VALUES (1,'Axis Bank');
INSERT INTO BANK(ID, NAME) VALUES (2,'Indian Bank');
SELECT * FROM BANK;


SELECT * FROM ACCOUNT; -- DELETE FROM ACCOUNT WHERE ID = 1;
INSERT INTO ACCOUNT (ID, BALANCE, BANK_ID) VALUES (1,100, 1);
INSERT INTO ACCOUNT (ID, BALANCE, BANK_ID) VALUES (2,100, 2);
INSERT INTO ACCOUNT (ID, BALANCE, BANK_ID) VALUES (3,100, 1);
INSERT INTO ACCOUNT (ID, BALANCE, BANK_ID) VALUES (4,100, 2);

SELECT * FROM BRANCH;
INSERT INTO BRANCH (ID, ADDRESS, BANK_ID) VALUES (1, 'Anna Nagar EAST, Chennai', 1);
INSERT INTO BRANCH (ID, ADDRESS, BANK_ID) VALUES (2, 'Adayar, Chennai', 1);
INSERT INTO BRANCH (ID, ADDRESS, BANK_ID) VALUES (3, 'V.O.C Nagar, Attur', 2)
INSERT INTO BRANCH (ID, ADDRESS, BANK_ID) VALUES (4, 'Gandhi Nagar, Koviipatti', 2);


SELECT BANK.NAME, BRANCH.ADDRESS FROM BANK, BRANCH WHERE BRANCH.BANK_ID = BANK.ID;

SELECT * FROM PERSON;
INSERT INTO PERSON(ID,NAME) VALUES (1, 'RAJESWARAN R');
INSERT INTO PERSON(ID,NAME) VALUES (2, 'SUJATHA K');

SELECT * FROM PERSON_ACCOUNTS;
INSERT INTO PERSON_ACCOUNTS(OWNERS_ID, ACCOUNTS_ID) VALUES (1, 2);

SELECT 
   P.NAME,
   A.BALANCE,
   B.NAME
FROM PERSON P 
LEFT JOIN PERSON_ACCOUNTS PA ON P.ID = PA.OWNERS_ID
LEFT JOIN ACCOUNT A ON A.ID = PA.ACCOUNTS_ID
LEFT JOIN BANK B ON A.ID = B.ID